In [12]:
import numpy as np
import pandas as pd

In [6]:
class Test:
    def __init__(self):
        self.a=0
    def abc(self):
        return self

In [7]:
c=Test()
c

<__main__.Test instance at 0x7f6c8c2f9a28>

In [10]:
c.abc()

<__main__.Test instance at 0x7f6c8c2f9a28>

In [11]:
c.abc()==c

True

In [15]:
a=np.zeros((2,4))
type(a)

numpy.ndarray

In [18]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [21]:
a.fill(2)
a

array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.]])

In [24]:
a.fill(4)
a

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])