In [3]:
df = ori.copy()
df.head()

id       name             address           city state    zip  \
0  1003609      jason      340 colby lane         ambler    PA    NaN   
1  1003610  angelique     2820 dudley ave          bronx    NY  10461   
2  1003611      Linda     164 Whiley Road         Groton    MA  01450   
3  1003613      bobby                 NaN         durham    NC    NaN   
4  1003614     monica  1611 east elmer rd  east vineland    NJ    NaN   

                       type                              source  \
0  Supercharged Phone Leads                      Organic Search   
1  Supercharged Phone Leads                      Organic Search   
2    Supercharged Web Leads                      Organic Search   
3  Supercharged Phone Leads                      Organic Search   
4  Supercharged Phone Leads  PPC Campaign (clicked on a PPC ad)   

              association            service_type        received_time  \
0  Basement Systems, Inc.       Foundation Repair  2007-08-01 08:09:22   
1  Basement Systems, Inc.  Basement Waterproofing  2007-08-01 08:13:17   
2  Basement Systems, Inc.  Basement Waterproofing  2007-08-01 08:51:41   
3  Basement Systems, Inc.  Basement Waterproofing  2007-08-01 08:10:26   
4  Basement Systems, Inc.  Basement Waterproofing  2007-08-01 09:31:39   

             sent_time                       company         status  price  \
0  2007-08-01 08:09:22           BQ Basement Systems  Billable Lead  100.0   
1  2007-08-01 08:13:17  Quality 1st Basement Systems  Billable Lead  100.0   
2  2007-08-01 08:51:41    Northeast Basement Systems  Billable Lead   60.0   
3  2007-08-01 08:10:26        Regional Waterproofing  Billable Lead   60.0   
4  2007-08-01 09:31:39     Dry Guys Basement Systems  Billable Lead  100.0   

         campaign  is_mobile landing_page contact_page previous_page  \
0  Phone Transfer        NaN          NaN          NaN           NaN   
1  Phone Transfer        NaN          NaN          NaN           NaN   
2             NaN        NaN          NaN          NaN           NaN   
3  Phone Transfer        NaN          NaN          NaN           NaN   
4             NaN        NaN          NaN          NaN           NaN   

   inbound_number call_status  duration  job_sold  
0             NaN         NaN       NaN       NaN  
1             NaN         NaN       NaN       NaN  
2             NaN         NaN       NaN       NaN  
3             NaN         NaN       NaN       NaN  
4             NaN         NaN       NaN       1.0

### null percentage of total

In [5]:
for i in df:
    m, n = ck_null(i), df.shape[0]
    print  str(m).ljust(8), n, str(round(m/float(n),4)*100).ljust(5)+' %', i

0        1243807 0.0   % id
3284     1243807 0.26  % name
68868    1243807 5.54  % address
3134     1243807 0.25  % city
0        1243807 0.0   % state
43797    1243807 3.52  % zip
0        1243807 0.0   % type
4        1243807 0.0   % source
367      1243807 0.03  % association
7111     1243807 0.57  % service_type
0        1243807 0.0   % received_time
0        1243807 0.0   % sent_time
172      1243807 0.01  % company
0        1243807 0.0   % status
0        1243807 0.0   % price
939164   1243807 75.51 % campaign
978626   1243807 78.68 % is_mobile
461169   1243807 37.08 % landing_page
613968   1243807 49.36 % contact_page
654039   1243807 52.58 % previous_page
699281   1243807 56.22 % inbound_number
699281   1243807 56.22 % call_status
699281   1243807 56.22 % duration
1221674  1243807 98.22 % job_sold


### unique values of each variable (compare to all value counts)

In [6]:
for i in df:
    m, n = ck_count_uniq(i), df.shape[0]
    print  str(m).ljust(8), n, str(round(m/float(n),4)*100).ljust(5)+' %', i

1243807  1243807 100.0 % id
132216   1243807 10.63 % name
1130816  1243807 90.92 % address
54170    1243807 4.36  % city
59       1243807 0.0   % state
109471   1243807 8.8   % zip
2        1243807 0.0   % type
17       1243807 0.0   % source
21       1243807 0.0   % association
227      1243807 0.02  % service_type
1232886  1243807 99.12 % received_time
1234264  1243807 99.23 % sent_time
825      1243807 0.07  % company
2        1243807 0.0   % status
1164     1243807 0.09  % price
59       1243807 0.0   % campaign
3        1243807 0.0   % is_mobile
190667   1243807 15.33 % landing_page
3586     1243807 0.29  % contact_page
39340    1243807 3.16  % previous_page
33665    1243807 2.71  % inbound_number
4        1243807 0.0   % call_status
1893     1243807 0.15  % duration
2        1243807 0.0   % job_sold


### fillin null value with a string

In [7]:
df = df.fillna('No Data')

### check the count of the variable we want to predict

In [8]:
ck_count('status')

Billable Lead    825202
No Charge        418605
Name: status, dtype: int64

### drop variables that may influence our predict variable

In [11]:
df= df.drop(['source', 'id','price', 'name', 'address', 'sent_time', 
             'sent_time', 'received_time', 'duration', 'job_sold', 'inbound_number'], axis=1)

### preprocessing data to numerical values

In [14]:
df.head()

city  state    zip  type  association  service_type  company  status  \
0  43379     44  71023     0            0            79       86       0   
1  44269     39   4182     0            0            23      620       0   
2  15030     21    886     1            0            23      551       0   
3  45713     31  71023     0            0            23      639       0   
4  45853     35  71023     0            0            23      299       0   

   campaign  is_mobile  landing_page  contact_page  previous_page  \
0        30          2             0             0              0   
1        30          2             0             0              0   
2        25          2             0             0              0   
3        30          2             0             0              0   
4        25          2             0             0              0   

   call_status  month  day  hour  
0            1      8    1     8  
1            1      8    1     8  
2            1      8    1     8  
3            1      8    1     8  
4            1      8    1     9

#### get target variable

In [15]:
mark = df.pop('status')
mark.shape

(1243807,)

### unique values of input (after preprocessing)

In [48]:
for i in df:
    m, n = ck_count_uniq(i), df.shape[0]
    print  str(m).ljust(8), n, str(round(m/float(n),4)*100).ljust(5)+' %', i

54170    1243807 4.36  % city
59       1243807 0.0   % state
109471   1243807 8.8   % zip
2        1243807 0.0   % type
21       1243807 0.0   % association
227      1243807 0.02  % service_type
825      1243807 0.07  % company
59       1243807 0.0   % campaign
3        1243807 0.0   % is_mobile
190667   1243807 15.33 % landing_page
3586     1243807 0.29  % contact_page
39340    1243807 3.16  % previous_page
4        1243807 0.0   % call_status
13       1243807 0.0   % month
32       1243807 0.0   % day
24       1243807 0.0   % hour


In [16]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

### train on 75% of and test on the remaining 25% of the data

In [19]:
X_train, X_test, y_train, y_test = train_test_split(df, mark, test_size=0.25, random_state=0)
dim(X_train, X_test, y_train, y_test)

[(932855, 16), (310952, 16), (932855,), (310952,)]

In [20]:
%%time
rf.fit(X_train, y_train)
rf

CPU times: user 41.8 s, sys: 44 ms, total: 41.9 s
Wall time: 43.1 s


In [21]:
pred = rf.predict(X_test)
print pred.shape
pred[:3]

(310952,)


array([0, 1, 1])

### model accuracy 


In [22]:
accuracy_score(y_test, pred)

0.72666520877820373

In [23]:
rf.feature_importances_

array([ 0.11662795,  0.03063017,  0.16759964,  0.00407409,  0.02923484,
        0.04488525,  0.05319541,  0.02766469,  0.01552473,  0.10823343,
        0.02899416,  0.03352382,  0.00797658,  0.09358678,  0.1293143 ,
        0.10893415])

In [24]:
forest = rf
import numpy as np
import matplotlib.pyplot as plt
X=X_train

### feature importance

In [4]:
plotting()

NameError: global name 'rf' is not defined

In [3]:
def plotting():
    forest=rf
    importances = forest.feature_importances_
    std = np.std([tree.feature_importances_ for tree in forest.estimators_],
                 axis=0)
    indices = np.argsort(importances)[::-1]



    # Plot the feature importances of the forest
    plt.figure(figsize=(16,8))
    plt.title("Feature importances")
    plt.barh(range(X.shape[1]), importances[indices],
           color="r", xerr=std[indices], 
            align="center", alpha=.7)

    plt.yticks(range(X.shape[1]), list(X.columns[indices]))
    plt.ylim([-1, X.shape[1]])

    plt.gca().invert_yaxis()

    plt.show()

    # Print the feature ranking
    print("Feature ranking:")
    for f in range(X.shape[1]):
        print("{}. feature {} ({:.2f} %)" .format (f + 1, X.columns[indices[f]], 100*importances[indices[f]]))

### cross validation

In [46]:
cross_val_score(rf, df.values, mark.values, cv=10)

array([ 0.70941937,  0.54113939,  0.66500511,  0.65254339,  0.61876814,
        0.60713137,  0.55130246,  0.45880367,  0.5588921 ,  0.62875864])

### pred by prob

In [47]:
rf.predict_proba(X_test)

array([[ 0.6,  0.4],
       [ 0. ,  1. ],
       [ 0.3,  0.7],
       ..., 
       [ 0. ,  1. ],
       [ 0.2,  0.8],
       [ 0.5,  0.5]])

In [49]:
pred

array([0, 1, 1, ..., 1, 1, 0])