In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.Series(np.random.random(100000))
df.shape

(100000,)

In [3]:
%%time
a = df.sort_values(ascending=False)

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 12.7 ms


In [11]:
arr = np.random.random(1280000).reshape(10000,128)
arr.shape

(10000, 128)

In [12]:
arr[0].shape

(128,)

In [13]:
arr.shape, arr[0].shape

((10000, 128), (128,))

In [14]:
arr[0].reshape(-1,1).shape

(128, 1)

In [15]:
# arr[0].reshape(1,-1)

In [16]:
%%time
result = cosine_similarity(arr[0].reshape(1,-1),arr)
b=pd.Series(result[0])
b=b.sort_values(ascending=False)

CPU times: user 16 ms, sys: 4 ms, total: 20 ms
Wall time: 14.6 ms


In [17]:
%%time
result = cosine_similarity(arr[0],arr)
b=pd.Series(result[0])
b=b.sort_values(ascending=False)

CPU times: user 16 ms, sys: 0 ns, total: 16 ms
Wall time: 12.5 ms


/home/saya/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [18]:
b[:10].index

Int64Index([0, 4797, 9453, 9720, 9699, 8606, 7011, 6122, 7759, 2610], dtype='int64')

In [19]:
def one(x,y):
    result=[]
    for i in range(len(y)):
        result.append(cosine_similarity(x.values.reshape(1,-1), y.iloc[i].values.reshape(1,-1))[0][0])
        sorting = pd.Series(result).sort_values(ascending=False)
    return sorting

In [20]:
x = pd.Series(arr[0])
y = pd.DataFrame(arr)

In [21]:
arr.shape

(10000, 128)

In [22]:
y.shape

(10000, 128)

In [23]:
type(arr)

numpy.ndarray

In [24]:
%%time
y.as_matrix()

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 62 µs


array([[ 0.22121856,  0.03844557,  0.18889388, ...,  0.41271781,
         0.52755848,  0.07236479],
       [ 0.47754335,  0.96126851,  0.46667608, ...,  0.74600242,
         0.76051803,  0.46447925],
       [ 0.24848846,  0.30854417,  0.13005951, ...,  0.63245137,
         0.5186961 ,  0.85558051],
       ..., 
       [ 0.34786672,  0.16247486,  0.4874992 , ...,  0.82394993,
         0.29325444,  0.00908708],
       [ 0.49269368,  0.84806385,  0.2464257 , ...,  0.52139186,
         0.64043367,  0.76471376],
       [ 0.99973545,  0.43691309,  0.40857017, ...,  0.0807745 ,
         0.80250903,  0.14664971]])

In [25]:
type(y.as_matrix())

numpy.ndarray

In [26]:
x.as_matrix()==arr[0]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True]

In [29]:
%%time 
c=one(x,y)

CPU times: user 17.1 s, sys: 0 ns, total: 17.1 s
Wall time: 17.1 s


In [ ]:
abs

In [30]:
tot=0
for i,j in zip(b,c):
    tot+=abs(i-j)

In [33]:
tot*1000000000000

0.45030645878796349

In [54]:
x.as_matrix().reshape[]

array([ 0.39838489,  0.270621  ,  0.11967334,  0.76374123,  0.65547935,
        0.94838216,  0.56432386,  0.08389938,  0.89132022,  0.48316755,
        0.49123879,  0.57089052,  0.41263953,  0.52658705,  0.48288937,
        0.38598601,  0.67756899,  0.11041126,  0.15125474,  0.12710974,
        0.68733057,  0.42773726,  0.68621121,  0.22782292,  0.15577681,
        0.18118842,  0.85504652,  0.15607439,  0.1154611 ,  0.43268882,
        0.04928459,  0.05559058,  0.0539609 ,  0.25934306,  0.13128847,
        0.66495571,  0.91444053,  0.28385314,  0.17322109,  0.39471907,
        0.62390665,  0.90450094,  0.67433513,  0.61033804,  0.20778756,
        0.48854874,  0.88282593,  0.42936548,  0.62134302,  0.82753573,
        0.11183069,  0.96714206,  0.15868627,  0.06739835,  0.36455131,
        0.91123926,  0.66901966,  0.91824441,  0.12782461,  0.39565135,
        0.80988087,  0.00788569,  0.73564613,  0.90987516,  0.297334  ,
        0.17133374,  0.09019381,  0.13746366,  0.42750582,  0.33