In [1]:
import sys

In [2]:
print (sys.version)

2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:16:05) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]


In [3]:
print (sys.version_info)

sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0)


In [4]:
!lscpu

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    1
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
Stepping:              2
CPU MHz:               2599.825
BogoMIPS:              5199.25
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23


In [20]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [21]:
l = LabelEncoder()
l

LabelEncoder()

In [25]:
print l.fit_transform([1,2,3,4,2,3,5,9,0, 'what','why'])
print l.classes_

[1 2 3 4 2 3 5 6 0 7 8]
['0' '1' '2' '3' '4' '5' '9' 'what' 'why']


In [26]:
l.transform([1,3,5,9, 'what'])

array([1, 3, 5, 6, 7])

https://stackoverflow.com/questions/40321232/handling-unknown-values-for-label-encoding

In [27]:
l.transform([1,7])

ValueError: y contains new labels: [1 7]

### one hot

In [28]:
import numpy as np

In [29]:
o = OneHotEncoder()
o

OneHotEncoder(categorical_features='all', dtype=<type 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [31]:
d = np.array([2,3,5,7,8]).reshape(-1,1)
d

array([[2],
       [3],
       [5],
       [7],
       [8]])

In [48]:
o.fit_transform(d)

<5x5 sparse matrix of type '<type 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [33]:
o.categorical_features

'all'

In [45]:
o.active_features_, o.dtype, o.feature_indices_, o.n_values, o.n_values_, o.handle_unknown

(array([2, 3, 5, 7, 8]),
 numpy.float64,
 array([0, 9]),
 'auto',
 array([9]),
 'error')

In [ ]:
o.transform