In [2]:
# !ls -hl|grep csv
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from time import time, ctime
from sklearn.metrics import accuracy_score, classification_report, classification, confusion_matrix
from sklearn.model_selection import train_test_split, KFold, cross_val_score, StratifiedKFold, StratifiedShuffleSplit
from helper import plot_confusion_matrix, plot_confusion_matrix2
dim=lambda *x: [i.shape for i in x]

import warnings
warnings.filterwarnings("ignore")

In [3]:
%%time
df = pd.read_csv('./preprocessed.csv')
print df.shape

(49260, 748)
CPU times: user 2.95 s, sys: 247 ms, total: 3.19 s
Wall time: 3.19 s


In [4]:
X = df.iloc[:,2:].values
print X.shape
y = df.iloc[:,1].map({'male':1,'female':0}).values
print y.shape
df.head(1)

(49260, 746)
(49260,)


username fname.gender username_split_predict last last_two first first2  \
0  billion         male                 unknow    n       on     b     bi   

   nchar  vowels.pct  digits.pct     ...       feature_721  feature_722  \
0      7    0.428571         0.0     ...               0.0          0.0   

   feature_723  feature_724  feature_725  feature_726  feature_727  \
0          0.0          0.0          0.0          0.0          0.0   

   feature_728  feature_729  feature_730  
0         13.0         14.0          7.0  

[1 rows x 748 columns]

In [5]:
%%time
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

for i in range(5):
    i=str(i)
    exec("labelencoder_X_{} = LabelEncoder()".format(i))
    exec("X[:, {}] = labelencoder_X_{}.fit_transform(X[:, {}])".format(i,i,i))

CPU times: user 146 ms, sys: 0 ns, total: 146 ms
Wall time: 145 ms


In [6]:
%%time
print X.shape
onehotencoder = OneHotEncoder(categorical_features = range(6))
X = onehotencoder.fit_transform(X).toarray()
print X.shape

(49260, 746)
(49260, 4505)
CPU times: user 1.34 s, sys: 481 ms, total: 1.82 s
Wall time: 1.82 s


In [7]:
%%time
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# fit on training set
X = sc.fit_transform(X)
print X.shape

(49260, 4505)
CPU times: user 2.96 s, sys: 1.54 s, total: 4.5 s
Wall time: 4.5 s


https://rasbt.github.io/mlxtend/user_guide/classifier/StackingClassifier/

In [12]:
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier

from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier,\
ExtraTreesClassifier, GradientBoostingClassifier, VotingClassifier, RandomForestClassifier

from mlxtend.classifier import StackingClassifier

import numpy as np

In [ ]:
from time import ctime()
ctime()

In [ ]:
clf1 = AdaBoostClassifier()
clf2 = RandomForestClassifier(random_state=1, n_estimators=320, min_samples_split=4, n_jobs=-1)
clf3 = XGBClassifier(nthread=-1, max_depth=24,
                        min_child_weight=0.9, colsample_bytree=0.9,
                       scale_pos_weight= 0.9, reg_alpha=0.6)
clf4 = BaggingClassifier(n_jobs=-1, n_estimators=50)
clf5 = ExtraTreesClassifier(n_jobs=-1, bootstrap=True, n_estimators=100)

lr = LogisticRegression(solver='lbfgs', n_jobs=-1)

sclf = StackingClassifier(classifiers=[clf1, clf2, clf3, clf4, clf5], 
                          meta_classifier=lr)

print('5-fold cross validation:\n')

if __name__ == '__main__':
    track1 = []
    for clf, label in zip([clf1, clf2, clf3, clf4, clf5,  sclf], 
                          ['AdaBoost', 
                           'Random Forest', 
                           'Xgboost',
                           'Bagging',
                           'ExtraTrees',
                           'Stacking']):

        scores = model_selection.cross_val_score(clf, X, y, 
#                                                  n_jobs=-1,
                                                  cv=5, scoring='accuracy')
        track1.append([label, scores, scores.mean(), scores.std()])
        print("Accuracy: %0.4f (+/- %0.4f) [%s]" 
              % (scores.mean(), scores.std(), label))

In [ ]:
from time import ctime()
t1 = ctime()

In [ ]:
clf1 = AdaBoostClassifier()
clf2 = RandomForestClassifier(random_state=1, n_estimators=320, min_samples_split=4, n_jobs=-1)
clf3 = XGBClassifier(nthread=-1, max_depth=24,
                        min_child_weight=0.9, colsample_bytree=0.9,
                       scale_pos_weight= 0.9, reg_alpha=0.6)
clf4 = BaggingClassifier(n_jobs=-1, n_estimators=50)
clf5 = ExtraTreesClassifier(n_jobs=-1, bootstrap=True, n_estimators=100)

lr = LogisticRegression(solver='lbfgs', n_jobs=-1)

sclf = StackingClassifier(classifiers=[clf1, clf2, clf3, clf4, clf5], 
                          meta_classifier=lr,
                          use_probas=True,
                          average_probas=False)

print('5-fold cross validation:\n')

if __name__ == '__main__':
    
    track2 = []
    for clf, label in zip([clf1, clf2, clf3, clf4, clf5,  sclf], 
                          ['AdaBoost', 
                           'Random Forest', 
                           'Xgboost',
                           'Bagging',
                           'ExtraTrees',
                           'Stacking']):

        scores = model_selection.cross_val_score(clf, X, y, 
                                                 n_jobs=-1,
                                                  cv=5, scoring='accuracy')
        track2.append([label, scores, scores.mean(), scores.std()])
        print("Accuracy: %0.4f (+/- %0.4f) [%s]" 
              % (scores.mean(), scores.std(), label))

5-fold cross validation:

Accuracy: 0.8237 (+/- 0.0008) [AdaBoost]
Accuracy: 0.8244 (+/- 0.0013) [Random Forest]
Accuracy: 0.8298 (+/- 0.0019) [Xgboost]


In [ ]:
t2=ctime()

In [16]:
track1

NameError: name 'track1' is not defined

In [ ]:
t1

In [17]:
track2

[['AdaBoost',
  array([ 0.82330255,  0.82511165,  0.8226756 ,  0.82369062,  0.8234697 ]),
  0.82365002369368789,
  0.00080507980493064015],
 ['Random Forest',
  array([ 0.82299807,  0.82592367,  0.82511165,  0.82521315,  0.82275911]),
  0.82440113197399723,
  0.0012764916941748496],
 ['Xgboost',
  array([ 0.82989952,  0.8317093 ,  0.8316078 ,  0.82917174,  0.82661659]),
  0.82980098897816001,
  0.001868275523513574],
 ['Bagging',
  array([ 0.82320106,  0.82886724,  0.82856273,  0.82551766,  0.82499239]),
  0.82622821338471475,
  0.0021730270412177351],
 ['ExtraTrees',
  array([ 0.82715924,  0.82785221,  0.82754771,  0.82632968,  0.82468785]),
  0.82671533756817106,
  0.0011350607926846686],
 ['Stacking',
  array([ 0.83040698,  0.83302883,  0.83384084,  0.82754771,  0.8267181 ]),
  0.83030849190249789,
  0.0028425443229955004]]